apiVersion: v1
kind: Namespace
metadata:
  name: "fluxcd"
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: sre-team
  name: flux-restricted
  namespace: "fluxcd"
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  labels:
#    toolkit.fluxcd.io/tenant: sre-team
#  name: flux-cluster-admin
#  namespace: "fluxcd"
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  labels:
#    toolkit.fluxcd.io/tenant: sre-team
#  name: flux-cluster-admin
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: cluster-admin
#subjects:
#  - kind: ServiceAccount
#    name: flux-cluster-admin
#    namespace: "fluxcd"
