apiVersion: v1
kind: Namespace
metadata:
  name: "cpa"
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: sre-team
  name: flux-restricted
  namespace: "cpa"