apiVersion: v1
kind: Namespace
metadata:
  name: "${APP_CODE}"
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: sre-team
  name: flux-restricted
  namespace: "${APP_CODE}"