apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cpa
  - ../../../../deploy/apps
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo
